###############################################
### Desclaimer: Only use this for debugging ###
###############################################

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:  postgres
      POSTGRES_DB: scraper
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass superSecret123
    volumes:
      - cache:/data

volumes:
  db_data:
  cache:
